[versions]
kotlin = "2.0.20"
compose = "1.6.11"
agp = "8.2.0"
intellij-plugin = "1.17.4"
changelog = "2.1.0"
intellij-platform = "2024.1"

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
jetbrainsIntellij = { id = "org.jetbrains.intellij", version.ref = "intellij-plugin" }
jetbrainsChangelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
